"""Shared, persistent storage for the Whiteboard card.

The card itself is pure frontend and would normally keep every board in the
browser's localStorage, which means one board per device. This integration
gives all the browsers in the house a single board: it keeps the strokes and
the objects in .storage and pushes every change to the other clients over the
websocket connection, so a drawing made on a phone shows up on the tablet.

Changes are merged per item, not per board. Each stroke and each object carries
an id generated by the client that created it, and clients send only what
changed, so two people drawing at the same time keep both drawings.
"""

from __future__ import annotations

import json
import logging
import time
from typing import Any, Callable

import voluptuous as vol

from homeassistant.components import websocket_api
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant, callback
from homeassistant.helpers.storage import Store
from homeassistant.helpers.typing import ConfigType

from .const import DOMAIN, MAX_BOARD_BYTES, SAVE_DELAY, STORAGE_KEY, STORAGE_VERSION

_LOGGER = logging.getLogger(__name__)

CONFIG_SCHEMA = vol.Schema({DOMAIN: vol.Schema({})}, extra=vol.ALLOW_EXTRA)


def _empty_board() -> dict[str, Any]:
    return {"rev": 0, "strokes": [], "objects": [], "updated": 0}


class BoardStore:
    """Holds every board and notifies the subscribed clients."""

    def __init__(self, hass: HomeAssistant) -> None:
        self._hass = hass
        self._store = Store[dict[str, Any]](hass, STORAGE_VERSION, STORAGE_KEY)
        self._boards: dict[str, dict[str, Any]] = {}
        self._listeners: dict[str, list[Callable[[dict[str, Any]], None]]] = {}

    async def async_load(self) -> None:
        data = await self._store.async_load()
        if isinstance(data, dict):
            boards = data.get("boards")
            if isinstance(boards, dict):
                self._boards = boards

    @callback
    def _schedule_save(self) -> None:
        self._store.async_delay_save(lambda: {"boards": self._boards}, SAVE_DELAY)

    @callback
    def snapshot(self, key: str) -> dict[str, Any]:
        board = self._boards.get(key) or _empty_board()
        return {
            "rev": board["rev"],
            "strokes": board["strokes"],
            "objects": board["objects"],
        }

    @callback
    def add_listener(
        self, key: str, listener: Callable[[dict[str, Any]], None]
    ) -> Callable[[], None]:
        self._listeners.setdefault(key, []).append(listener)

        @callback
        def remove() -> None:
            listeners = self._listeners.get(key)
            if not listeners:
                return
            if listener in listeners:
                listeners.remove(listener)
            if not listeners:
                self._listeners.pop(key, None)

        return remove

    @callback
    def _notify(self, key: str, payload: dict[str, Any]) -> None:
        for listener in list(self._listeners.get(key, [])):
            try:
                listener(payload)
            except Exception:  # noqa: BLE001 - one bad client must not stop the rest
                _LOGGER.exception("Whiteboard listener failed")

    @callback
    def apply(self, key: str, delta: dict[str, Any], client_id: str) -> dict[str, Any]:
        """Merge a delta into a board and tell everyone else about it."""
        board = self._boards.setdefault(key, _empty_board())

        if delta.get("clear"):
            board["strokes"] = []
            board["objects"] = []

        removed = set(delta.get("remove") or [])
        if removed:
            board["strokes"] = [s for s in board["strokes"] if s.get("id") not in removed]
            board["objects"] = [o for o in board["objects"] if o.get("id") not in removed]

        for stroke in delta.get("strokes") or []:
            if not stroke.get("id"):
                continue
            board["strokes"] = [s for s in board["strokes"] if s.get("id") != stroke["id"]]
            board["strokes"].append(stroke)

        for obj in delta.get("objects") or []:
            if not obj.get("id"):
                continue
            replaced = False
            for index, existing in enumerate(board["objects"]):
                if existing.get("id") == obj["id"]:
                    board["objects"][index] = obj
                    replaced = True
                    break
            if not replaced:
                board["objects"].append(obj)

        size = len(json.dumps(board, separators=(",", ":")))
        if size > MAX_BOARD_BYTES:
            # Undo this delta rather than storing a board we cannot keep.
            for stroke in delta.get("strokes") or []:
                board["strokes"] = [s for s in board["strokes"] if s.get("id") != stroke.get("id")]
            for obj in delta.get("objects") or []:
                board["objects"] = [o for o in board["objects"] if o.get("id") != obj.get("id")]
            raise BoardTooLarge(size)

        board["rev"] += 1
        board["updated"] = time.time()
        self._schedule_save()

        self._notify(
            key,
            {
                "rev": board["rev"],
                "client_id": client_id,
                "clear": bool(delta.get("clear")),
                "remove": list(removed),
                "strokes": delta.get("strokes") or [],
                "objects": delta.get("objects") or [],
            },
        )
        return {"rev": board["rev"]}


class BoardTooLarge(Exception):
    """Raised when a board would exceed MAX_BOARD_BYTES."""

    def __init__(self, size: int) -> None:
        super().__init__(f"board would be {size} bytes")
        self.size = size


async def async_setup(hass: HomeAssistant, config: ConfigType) -> bool:
    """Register the websocket API once, whatever way the component is loaded."""
    websocket_api.async_register_command(hass, ws_get)
    websocket_api.async_register_command(hass, ws_apply)
    websocket_api.async_register_command(hass, ws_subscribe)
    return True


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    store = BoardStore(hass)
    await store.async_load()
    hass.data[DOMAIN] = store
    return True


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    hass.data.pop(DOMAIN, None)
    return True


def _store(hass: HomeAssistant) -> BoardStore | None:
    store = hass.data.get(DOMAIN)
    return store if isinstance(store, BoardStore) else None


@websocket_api.websocket_command(
    {
        vol.Required("type"): "ha_whiteboard/get",
        vol.Required("key"): str,
    }
)
@callback
def ws_get(hass: HomeAssistant, connection, msg: dict[str, Any]) -> None:
    """Return the full board."""
    store = _store(hass)
    if store is None:
        connection.send_error(msg["id"], "not_ready", "Whiteboard storage is not set up")
        return
    connection.send_result(msg["id"], store.snapshot(msg["key"]))


@websocket_api.websocket_command(
    {
        vol.Required("type"): "ha_whiteboard/apply",
        vol.Required("key"): str,
        vol.Required("client_id"): str,
        vol.Optional("clear", default=False): bool,
        vol.Optional("remove", default=list): [str],
        vol.Optional("strokes", default=list): [dict],
        vol.Optional("objects", default=list): [dict],
    }
)
@callback
def ws_apply(hass: HomeAssistant, connection, msg: dict[str, Any]) -> None:
    """Merge a change coming from one of the clients."""
    store = _store(hass)
    if store is None:
        connection.send_error(msg["id"], "not_ready", "Whiteboard storage is not set up")
        return
    try:
        result = store.apply(
            msg["key"],
            {
                "clear": msg["clear"],
                "remove": msg["remove"],
                "strokes": msg["strokes"],
                "objects": msg["objects"],
            },
            msg["client_id"],
        )
    except BoardTooLarge as err:
        connection.send_error(msg["id"], "too_large", str(err))
        return
    connection.send_result(msg["id"], result)


@websocket_api.websocket_command(
    {
        vol.Required("type"): "ha_whiteboard/subscribe",
        vol.Required("key"): str,
    }
)
@callback
def ws_subscribe(hass: HomeAssistant, connection, msg: dict[str, Any]) -> None:
    """Stream every change made to a board."""
    store = _store(hass)
    if store is None:
        connection.send_error(msg["id"], "not_ready", "Whiteboard storage is not set up")
        return

    @callback
    def forward(payload: dict[str, Any]) -> None:
        connection.send_message(websocket_api.event_message(msg["id"], payload))

    connection.subscriptions[msg["id"]] = store.add_listener(msg["key"], forward)
    connection.send_result(msg["id"])
